name: Push to main + docs branches

on:
  workflow_dispatch:

jobs:
  push_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
          ref: 'develop'
          fetch-depth: 0

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e
        with:
          app-id: 894214
          private-key: ${{ secrets.THIRDWEB_BOT_PRIVATE_KEY }}

      - name: Push to main + docs branches
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
            git push origin develop:main --force
            git push origin develop:docs --force
